env:
  browser: true
  es6: true
  jquery: false
  node: true
parserOptions:
  sourceType: script
  parser: babel-eslint
extends:
  - plugin:vue/recommended
plugins:
  - vue
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
  no-console:
    - warn
    - allow: error
  no-unused-vars:
    - error
  no-undef:
    - error
  func-call-spacing:
    - error
    - never
