env:
  browser: true
  es6: true
  jquery: true
parserOptions:
  sourceType: script
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
  no-console:
    - 0
  no-unused-vars:
    - error
  no-undef:
    - error
  func-call-spacing:
    - error
    - never
