# env:
#   browser: true
#   es6: true
#   jquery: false
#   node: true
extends:
  - plugin:vue/vue3-recommended
  - eslint:recommended
plugins:
  - vue
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-console:
    - warn
    - allow:
      - error
  no-unused-vars:
    - error
  no-undef:
    - error
  func-call-spacing:
    - error
    - never
  sort-imports:
    - warn
    - ignoreCase: true
