version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    working_directory: ~/www.millergeek.xyz
    steps:
      - checkout
      - restore_cache:
          keys:
            # Find a cache corresponding to this specific yarn.lock checksum
            - v1-deps-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
            # Find a cache corresponding to this specific package.json checksum
            - v1-deps-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
            # Find the most recent cache used from this branch
            - v1-deps-{{ arch }}-{{ .Branch }}
            # Find the most recent cache used from master
            - v1-deps-{{ arch }}-master
      - run:
          name: Install global npm dependencies
          command: yarn
          no_output_timeout: 3m
      - run:
          name: Install npm dependencies
          command: yarn
          no_output_timeout: 3m
      # - run:
      #     name: Install other dependencies
      #     command: apt-get install -y libjpeg libpng
      #     no_output_timeout: 3m
      - run:
          name: Run linter
          command: yarn lint --format junit -o reports/junit/js-lint-results.xml
          no_output_timeout: 1m
      - run:
          name: Build site
          command: yarn build
          no_output_timeout: 1m
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit
      - save_cache:
          key: v1-deps-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - .cache
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              yarn deploy;
            else
              echo "Not master branch so not deploying"
            fi
